### ISSUE TITLE
Require it with an explicit version constraint allowing its       desired stability

### ISSUE THREAD

**Issue by Ebad-ur-Rehman** [kduma-OSS/laravel-soap-server#1]
[InvalidArgumentException]
  Could not find a version of package kduma/laravel-soap-server matching your minimu   
  m-stability (stable). Require it with an explicit version constraint allowing its    
  desired stability.

**Comment by kduma** [comment]
At this moment there is no published version. At this moment you can import it as `composer require kduma/laravel-soap-server:dev-master`

**Comment by Ebad-ur-Rehman** [comment]
> At this moment there is no published version. At this moment you can import it as `composer require kduma/laravel-soap-server:dev-master`

Thanks man

**Comment by kduma** [comment]
This package is unfortunetely based on [laminas-soap](https://github.com/laminas/laminas-soap) package, which is now in security maintainance only stage, and in current state is somewhat flicky in usage. I have a plan to redo my package based on PHP SOAP extension it the future.
